import React, { useState } from 'react';
import {
  X,
  Upload,
  FileText,
  CheckCircle2,
} from 'lucide-react';
import { RAGDocument, DocumentChunk } from '../types/agent';
import { splitTextIntoChunks } from '../services/ragPipeline';
import { qdrantStore } from '../services/qdrantStore';

interface DocumentUploadModalProps {
  isOpen: boolean;
  onClose: () => void;
  onDocumentAdded: (doc: RAGDocument, chunks: DocumentChunk[]) => void;
  chunkSize: number;
  chunkOverlap: number;
}

export const DocumentUploadModal: React.FC<DocumentUploadModalProps> = ({
  isOpen,
  onClose,
  onDocumentAdded,
  chunkSize,
  chunkOverlap,
}) => {
  const [title, setTitle] = useState('');
  const [filename, setFilename] = useState('');
  const [text, setText] = useState('');
  const [tags, setTags] = useState('Agent, RAG, Qdrant');
  const [isProcessing, setIsProcessing] = useState(false);
  const [previewChunks, setPreviewChunks] = useState<DocumentChunk[]>([]);

  if (!isOpen) return null;

  const sampleTemplates = [
    {
      title: 'Production Multi-Agent Systems & Tool Orchestration',
      filename: 'Multi_Agent_Tool_Orchestration.pdf',
      tags: 'Agents, Tools, LangGraph',
      text: `Modern enterprise agent architectures employ distributed tool registries. When a user issues a complex command, the Master Orchestrator evaluates intent, resolves dependencies, and routes sub-tasks to specialized domain agents.

Each tool call is strictly governed by a JSON Schema. For stateful mutations such as updating customer records or issuing external emails, the agent emits an interruption signal, suspending the graph execution and persisting state to the checkpoint database.

Upon receiving human verification (Human-in-the-Loop signature), the checkpoint is reloaded, and execution resumes from the exact interruption node without losing previous chain-of-thought scratchpad context.`,
    },
    {
      title: 'HNSW Graph Optimization & Cosine Similarity in Qdrant',
      filename: 'Qdrant_HNSW_Optimization_Spec.pdf',
      tags: 'Qdrant, HNSW, Cosine, Embeddings',
      text: `Qdrant utilizes Hierarchical Navigable Small World (HNSW) graphs to perform nearest neighbor searches with sub-15ms latency across millions of dense vectors.

Vectors generated by Hugging Face sentence-transformers models are L2 normalized to ensure unit length. Under unit length constraints, cosine similarity is proportional to the standard dot product, allowing SIMD hardware acceleration and rapid ranking across multi-tenant collections.

Payload indexing allows combining vector proximity with structured metadata filters (tenant_id, document_security_tier), eliminating post-filtering overhead.`,
    },
  ];

  const handleSelectTemplate = (tmpl: typeof sampleTemplates[0]) => {
    setTitle(tmpl.title);
    setFilename(tmpl.filename);
    setTags(tmpl.tags);
    setText(tmpl.text);

    const docId = `doc_${Date.now()}`;
    const chunks = splitTextIntoChunks(tmpl.text, chunkSize, chunkOverlap, tmpl.title, docId);
    setPreviewChunks(chunks);
  };

  const handleTextChange = (val: string) => {
    setText(val);
    if (val.length > 50) {
      const docId = `doc_${Date.now()}`;
      const chunks = splitTextIntoChunks(val, chunkSize, chunkOverlap, title || 'Custom Document', docId);
      setPreviewChunks(chunks);
    } else {
      setPreviewChunks([]);
    }
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setFilename(file.name);
    setTitle(file.name.replace(/\.[^/.]+$/, '').replace(/[_-]/g, ' '));

    const reader = new FileReader();
    reader.onload = (event) => {
      const content = event.target?.result as string;
      handleTextChange(content);
    };
    reader.readAsText(file);
  };

  const handleIndexDocument = () => {
    if (!title.trim() || !text.trim()) return;

    setIsProcessing(true);

    setTimeout(() => {
      const docId = `doc_${Date.now()}`;
      const chunks = splitTextIntoChunks(text, chunkSize, chunkOverlap, title, docId);

      const newDoc: RAGDocument = {
        id: docId,
        title,
        filename: filename || `${title.toLowerCase().replace(/\s+/g, '_')}.pdf`,
        fileSize: `${(text.length / 1024).toFixed(1)} KB`,
        pageCount: Math.max(1, Math.ceil(chunks.length / 2)),
        uploadDate: new Date().toISOString().split('T')[0],
        chunksCount: chunks.length,
        status: 'indexed',
        tags: tags.split(',').map((t) => t.trim()).filter(Boolean),
        summary: text.slice(0, 160) + '...',
        fullText: text,
      };

      qdrantStore.upsertPoints('knowledge_pdf_docs', chunks);

      onDocumentAdded(newDoc, chunks);
      setIsProcessing(false);
      onClose();
    }, 600);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md select-none animate-in fade-in">
      <div className="relative w-full max-w-2xl rounded-3xl bg-[#11141e] border border-slate-800 shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-800 flex items-center justify-between bg-slate-900/40">
          <div className="flex items-center gap-2.5">
            <Upload className="w-5 h-5 text-cyan-400" />
            <h2 className="text-base font-bold text-white tracking-wide">
              Index Document into Qdrant Vector Store
            </h2>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Content body */}
        <div className="flex-1 overflow-y-auto p-6 space-y-4 text-xs">
          {/* Quick template pickers */}
          <div className="space-y-1.5">
            <label className="text-slate-300 font-medium">
              Load Sample Technical Whitepapers:
            </label>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              {sampleTemplates.map((tmpl, idx) => (
                <button
                  key={idx}
                  onClick={() => handleSelectTemplate(tmpl)}
                  className="text-left p-2.5 rounded-xl bg-slate-900/60 hover:bg-slate-850 border border-slate-800 hover:border-slate-700 text-[11px] text-slate-200 transition-all cursor-pointer"
                >
                  <div className="font-bold truncate text-white">{tmpl.title}</div>
                  <div className="text-[10px] text-slate-400 font-mono mt-0.5">
                    {tmpl.filename}
                  </div>
                </button>
              ))}
            </div>
          </div>

          {/* Upload or Drop Area */}
          <div className="p-4 rounded-2xl border border-dashed border-slate-700 hover:border-cyan-500/50 bg-slate-900/30 transition-colors text-center cursor-pointer relative">
            <input
              type="file"
              accept=".pdf,.txt,.md,.json"
              onChange={handleFileUpload}
              className="absolute inset-0 opacity-0 cursor-pointer"
            />
            <FileText className="w-8 h-8 text-cyan-400 mx-auto mb-2" />
            <div className="font-semibold text-white">
              Choose a PDF, TXT or Markdown file
            </div>
            <p className="text-[11px] text-slate-400 mt-0.5">
              Files will be split into {chunkSize}-token chunks with {chunkOverlap}-token overlap.
            </p>
          </div>

          {/* Title & Metadata */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <label className="block text-slate-300 font-medium mb-1">
                Document Title
              </label>
              <input
                type="text"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="e.g. Enterprise RAG Design Patterns"
                className="w-full p-2.5 rounded-xl bg-slate-900 border border-slate-700 text-white focus:outline-none focus:border-cyan-500"
              />
            </div>

            <div>
              <label className="block text-slate-300 font-medium mb-1">
                Tags (Comma separated)
              </label>
              <input
                type="text"
                value={tags}
                onChange={(e) => setTags(e.target.value)}
                placeholder="RAG, Embeddings, HITL"
                className="w-full p-2.5 rounded-xl bg-slate-900 border border-slate-700 text-white focus:outline-none focus:border-cyan-500"
              />
            </div>
          </div>

          {/* Text Area */}
          <div>
            <label className="block text-slate-300 font-medium mb-1">
              Document Text Body (for chunking & embedding)
            </label>
            <textarea
              value={text}
              onChange={(e) => handleTextChange(e.target.value)}
              rows={4}
              placeholder="Paste raw text here or select a template above..."
              className="w-full p-2.5 rounded-xl bg-slate-900 border border-slate-700 text-white font-mono text-[11px] focus:outline-none focus:border-cyan-500"
            />
          </div>

          {/* Live Chunks Preview */}
          {previewChunks.length > 0 && (
            <div className="space-y-2 pt-2 border-t border-slate-800">
              <div className="flex items-center justify-between text-[11px] font-bold uppercase tracking-wider text-slate-300">
                <span>
                  Live Chunking Preview ({previewChunks.length} chunks generated)
                </span>
                <span className="font-mono text-cyan-400">
                  Embeddings: MiniLM-L6-v2 (384-dim)
                </span>
              </div>

              <div className="space-y-2 max-h-36 overflow-y-auto pr-1">
                {previewChunks.map((chunk, idx) => (
                  <div
                    key={idx}
                    className="p-2.5 rounded-xl bg-slate-900 border border-slate-800 text-[11px] font-mono space-y-1"
                  >
                    <div className="flex justify-between text-cyan-400 text-[10px]">
                      <span>Chunk #{idx + 1}</span>
                      <span>{chunk.tokenCount} tokens • Page {chunk.page}</span>
                    </div>
                    <p className="text-slate-300 font-sans text-xs line-clamp-2">
                      {chunk.text}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-slate-800 bg-slate-900/40 flex items-center justify-between">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl text-xs text-slate-400 hover:text-white"
          >
            Cancel
          </button>

          <button
            onClick={handleIndexDocument}
            disabled={!title.trim() || !text.trim() || isProcessing}
            className="flex items-center gap-2 px-5 py-2 rounded-xl bg-cyan-600 hover:bg-cyan-500 text-xs font-bold text-white transition-all shadow-md cursor-pointer disabled:opacity-50"
          >
            {isProcessing ? (
              <>
                <div className="w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin" />
                <span>Generating Embeddings & Upserting...</span>
              </>
            ) : (
              <>
                <CheckCircle2 className="w-4 h-4" />
                <span>Index into Qdrant</span>
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};
